+incdir+$PRJ_PATH/verify
$PRJ_PATH/rtl/toy_pack.sv
$PRJ_PATH/rtl/cmn_lead_one.sv
$PRJ_PATH/rtl/cmn_onehot2bin.sv
$PRJ_PATH/rtl/mem/toy_mem_model_bit.sv
$PRJ_PATH/rtl/icache_top.sv
$PRJ_PATH/rtl/cmn_onehot2bin2.sv
$PRJ_PATH/rtl/icache_req_arbiter.sv
$PRJ_PATH/rtl/icache_tag_array_ctrl.sv
$PRJ_PATH/rtl/icache_mshr_entry.sv
$PRJ_PATH/rtl/icache_mshr_file.sv
$PRJ_PATH/rtl/icache_data_array_ctrl.sv
$PRJ_PATH/rtl/pre_allocate.sv
$PRJ_PATH/rtl/vrp_arb.sv
$PRJ_PATH/rtl/v_en_decode.sv
$PRJ_PATH/rtl/cmn_real_mux_onehot.sv
$PRJ_PATH/rtl/arb_vrp.sv
$PRJ_PATH/rtl/arb_fp.sv

$PRJ_PATH/verify/transaction/
$PRJ_PATH/verify/driver/
$PRJ_PATH/verify/monitor/
$PRJ_PATH/verify/ref_model/
$PRJ_PATH/verify/scoreboard/
$PRJ_PATH/verify/sequencer/