// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vicache_top.h for the primary calling header

#ifndef VERILATED_VICACHE_TOP___024ROOT_H_
#define VERILATED_VICACHE_TOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vicache_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vicache_top___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(prefetch_enable,0,0);
        VL_OUT8(upstream_txdat_vld,0,0);
        VL_OUT8(upstream_txdat_txnid,4,0);
        VL_IN8(upstream_txdat_rdy,0,0);
        VL_IN8(upstream_rxreq_vld,0,0);
        VL_OUT8(upstream_rxreq_rdy,0,0);
        VL_IN8(downstream_rxsnp_vld,0,0);
        VL_OUT8(downstream_rxsnp_rdy,0,0);
        VL_OUT8(downstream_txreq_vld,0,0);
        VL_IN8(downstream_txreq_rdy,0,0);
        VL_OUT8(downstream_txreq_entry_id,3,0);
        VL_IN8(downstream_txrsp_vld,0,0);
        VL_OUT8(downstream_txrsp_rdy,0,0);
        VL_IN8(downstream_txrsp_opcode,4,0);
        VL_IN8(downstream_rxdat_vld,0,0);
        VL_OUT8(downstream_rxdat_rdy,0,0);
        VL_IN8(prefetch_req_vld,0,0);
        VL_IN8(pref_to_mshr_req_rdy,0,0);
        CData/*0:0*/ icache_top__DOT__tag_req_vld;
        CData/*0:0*/ icache_top__DOT__tag_req_rdy;
        CData/*0:0*/ icache_top__DOT__tag_miss;
        CData/*1:0*/ icache_top__DOT__tag_hit;
        CData/*0:0*/ icache_top__DOT__lru_pick;
        CData/*0:0*/ icache_top__DOT__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__linefill_done;
        CData/*3:0*/ icache_top__DOT__alloc_index;
        CData/*0:0*/ icache_top__DOT__mshr_update_en;
        CData/*4:0*/ icache_top__DOT____Vcellout__u_icache_mshr_file__entry_release_done_index;
        CData/*0:0*/ icache_top__DOT__tag_way0_hit;
        CData/*0:0*/ icache_top__DOT__tag_way1_hit;
        CData/*0:0*/ icache_top__DOT__rd_vld;
        CData/*2:0*/ icache_top__DOT__u_icache_req_arbiter__DOT__arbiter__DOT__u_mux__DOT____VdfgRegularize_hd505c857_0_16;
        CData/*2:0*/ icache_top__DOT__u_icache_req_arbiter__DOT__arbiter__DOT__u_mux__DOT____VdfgRegularize_hd505c857_0_17;
        CData/*2:0*/ icache_top__DOT__u_icache_req_arbiter__DOT__arbiter__DOT__u_mux__DOT____VdfgRegularize_hd505c857_0_18;
        CData/*2:0*/ icache_top__DOT__u_icache_req_arbiter__DOT__arbiter__DOT__u_mux__DOT____VdfgRegularize_hd505c857_0_19;
        CData/*2:0*/ icache_top__DOT__u_icache_req_arbiter__DOT__arbiter__DOT__u_mux__DOT____VdfgRegularize_hd505c857_0_20;
        CData/*2:0*/ icache_top__DOT__u_icache_req_arbiter__DOT__arbiter__DOT__u_mux__DOT____VdfgRegularize_hd505c857_0_21;
        CData/*2:0*/ icache_top__DOT__u_icache_req_arbiter__DOT__arbiter__DOT__u_mux__DOT____VdfgRegularize_hd505c857_0_22;
        CData/*2:0*/ icache_top__DOT__u_icache_req_arbiter__DOT__arbiter__DOT__u_mux__DOT____VdfgRegularize_hd505c857_0_23;
        CData/*0:0*/ icache_top__DOT__u_icache_tag_array_ctrl__DOT__wr_tag_buf_vld;
        CData/*7:0*/ icache_top__DOT__u_icache_tag_array_ctrl__DOT__wr_tag_buf_index;
        CData/*0:0*/ icache_top__DOT__u_icache_tag_array_ctrl__DOT__req_vld;
        CData/*3:0*/ icache_top__DOT__u_icache_mshr_file__DOT__taken_index;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__0__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__0__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__1__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__1__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__2__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__2__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__3__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__3__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__4__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__4__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__5__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__5__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__6__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__6__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__7__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__7__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__8__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__8__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__9__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
    };
    struct {
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__9__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__10__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__10__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__11__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__11__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__12__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__12__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__13__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__13__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__14__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__14__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__15__KET____DOT__u_icache_mshr_entry__downstream_txreq_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__15__KET____DOT__u_icache_mshr_entry__dataram_rd_vld;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__0__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__0__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__0__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__0__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__0__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__0__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__0__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__1__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__1__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__1__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__1__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__1__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__1__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__1__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__2__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__2__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__2__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__2__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__2__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__2__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__2__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__3__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__3__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__3__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__3__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__3__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__3__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__3__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__4__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__4__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__4__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__4__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__4__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__4__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__4__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__5__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__5__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__5__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__5__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__5__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__5__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__5__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__6__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__6__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__6__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__6__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__6__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__6__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__6__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__7__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__7__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
    };
    struct {
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__7__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__7__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__7__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__7__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__7__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__8__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__8__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__8__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__8__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__8__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__8__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__8__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__9__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__9__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__9__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__9__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__9__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__9__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__9__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__10__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__10__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__10__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__10__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__10__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__10__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__10__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__11__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__11__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__11__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__11__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__11__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__11__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__11__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__12__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__12__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__12__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__12__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__12__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__12__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__12__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__13__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__13__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__13__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__13__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__13__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__13__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__13__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__14__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__14__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__14__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__14__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__14__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__14__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__14__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__15__KET____DOT__u_icache_mshr_entry__DOT__linefill_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__15__KET____DOT__u_icache_mshr_entry__DOT__linefill_data_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__15__KET____DOT__u_icache_mshr_entry__DOT__state_done;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__15__KET____DOT__u_icache_mshr_entry__DOT__state_rd_dataram_sent;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__15__KET____DOT__u_icache_mshr_entry__DOT__allocate_en;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__15__KET____DOT__u_icache_mshr_entry__DOT__hazard_free;
        CData/*0:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__15__KET____DOT__u_icache_mshr_entry__DOT__mshr_entry_array_valid;
        CData/*4:0*/ icache_top__DOT__u_data_array_ctrl__DOT__linefill_done_txnid;
        CData/*4:0*/ icache_top__DOT__u_data_array_ctrl__DOT__dataram_rd_txnid_out;
        CData/*0:0*/ icache_top__DOT__u_data_array_ctrl__DOT__dataram_dout_vld;
    };
    struct {
        CData/*0:0*/ icache_top__DOT__u_data_array_ctrl__DOT__linefill_data_vld;
        CData/*1:0*/ __VdfgRegularize_hd87f99a1_0_9;
        CData/*0:0*/ __Vdly__icache_top__DOT__u_icache_tag_array_ctrl__DOT__wr_tag_buf_vld;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ icache_top__DOT__v_linefill_done;
        SData/*15:0*/ icache_top__DOT__bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__v_entry_en;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__v_alloc_vld;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__v_alloc_rdy;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__v_dataram_rd_vld;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__v_dataram_rd_rdy;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__v_downstream_txreq_rdy;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__v_release_en;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_pre_allocate__DOT__v_vld_reg;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__v_grant;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_0;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_1;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_2;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_3;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_4;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_5;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_6;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_7;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_8;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_9;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_10;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_11;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_12;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT____VdfgRegularize_hf70afea1_0_13;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__u_downstream_rd_arb__DOT__v_grant;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__0__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__1__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__2__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__3__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__4__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__5__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__6__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__7__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__8__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__9__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__10__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__11__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__12__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__13__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__14__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        SData/*15:0*/ icache_top__DOT__u_icache_mshr_file__DOT__MSHR_ENTRY_ARRAY__BRA__15__KET____DOT__u_icache_mshr_entry__DOT__v_hazard_bitmap;
        VL_OUTW(upstream_txdat_data,511,0,16);
        VlWide<8>/*255:0*/ icache_top__DOT__u_icache_tag_array_ctrl__DOT__lru;
        VlWide<8>/*255:0*/ icache_top__DOT__u_data_array_ctrl__DOT__data_array0_dout;
        VlWide<8>/*255:0*/ icache_top__DOT__u_data_array_ctrl__DOT__data_array1_dout;
        VlWide<16>/*511:0*/ icache_top__DOT__u_data_array_ctrl__DOT__linefill_data;
        VlWide<8>/*255:0*/ icache_top__DOT__u_data_array_ctrl__DOT__u_icache_data_array0__DOT__tmp_data;
        VlWide<8>/*255:0*/ icache_top__DOT__u_data_array_ctrl__DOT__u_icache_data_array0__DOT__read_memory__Vstatic__data;
        VlWide<8>/*255:0*/ icache_top__DOT__u_data_array_ctrl__DOT__u_icache_data_array1__DOT__tmp_data;
        VlWide<8>/*255:0*/ icache_top__DOT__u_data_array_ctrl__DOT__u_icache_data_array1__DOT__read_memory__Vstatic__data;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(upstream_rxreq_pld,41,0);
        VL_IN64(downstream_rxsnp_pld,41,0);
        VL_OUT64(downstream_txreq_pld,41,0);
        VL_INW(downstream_rxdat_pld,525,0,17);
    };
    struct {
        VL_IN64(prefetch_req_pld,41,0);
        QData/*41:0*/ icache_top__DOT__tag_req_pld;
        QData/*42:0*/ icache_top__DOT__entry_data;
        QData/*37:0*/ icache_top__DOT__u_icache_tag_array_ctrl__DOT__tag_array0_dout;
        QData/*37:0*/ icache_top__DOT__u_icache_tag_array_ctrl__DOT__wr_tag_buf_pld;
        QData/*41:0*/ icache_top__DOT__u_icache_tag_array_ctrl__DOT__req_pld;
        QData/*37:0*/ icache_top__DOT__u_icache_tag_array_ctrl__DOT__u_icache_tag_array0__DOT__tmp_data;
        QData/*37:0*/ icache_top__DOT__u_icache_tag_array_ctrl__DOT__u_icache_tag_array0__DOT__read_memory__Vstatic__data;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__0__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__1__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__2__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__3__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__4__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__5__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__6__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__7__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__8__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__9__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__10__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__11__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__12__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__13__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__14__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        QData/*62:0*/ icache_top__DOT__u_icache_mshr_file__DOT____Vcellout__MSHR_ENTRY_ARRAY__BRA__15__KET____DOT__u_icache_mshr_entry__mshr_entry_array;
        VlUnpacked<QData/*62:0*/, 16> icache_top__DOT__v_mshr_entry_array;
        VlUnpacked<QData/*41:0*/, 3> icache_top__DOT__u_icache_req_arbiter__DOT__v_pld_s;
        VlUnpacked<QData/*41:0*/, 3> icache_top__DOT__u_icache_req_arbiter__DOT____Vcellinp__arbiter__v_pld_s;
        VlUnpacked<CData/*2:0*/, 42> icache_top__DOT__u_icache_req_arbiter__DOT__arbiter__DOT__u_mux__DOT__v_pld_rev;
        VlUnpacked<SData/*13:0*/, 16> icache_top__DOT__u_icache_mshr_file__DOT__v_dataram_rd_pld;
        VlUnpacked<QData/*41:0*/, 16> icache_top__DOT__u_icache_mshr_file__DOT__v_downstream_txreq_pld;
        VlUnpacked<SData/*13:0*/, 16> icache_top__DOT__u_icache_mshr_file__DOT____Vcellinp__u_dataram_rd_arb__v_pld_s;
        VlUnpacked<QData/*41:0*/, 16> icache_top__DOT__u_icache_mshr_file__DOT____Vcellinp__u_downstream_rd_arb__v_pld_s;
        VlUnpacked<SData/*15:0*/, 14> icache_top__DOT__u_icache_mshr_file__DOT__u_dataram_rd_arb__DOT__u_mux__DOT__v_pld_rev;
        VlUnpacked<SData/*15:0*/, 42> icache_top__DOT__u_icache_mshr_file__DOT__u_downstream_rd_arb__DOT__u_mux__DOT__v_pld_rev;
    };
    VlAssocArray<SData/*8:0*/, VlWide<8>/*255:0*/> icache_top__DOT__u_data_array_ctrl__DOT__u_icache_data_array0__DOT__memory;
    VlAssocArray<SData/*8:0*/, VlWide<8>/*255:0*/> icache_top__DOT__u_data_array_ctrl__DOT__u_icache_data_array1__DOT__memory;
    VlAssocArray<CData/*7:0*/, QData/*37:0*/> icache_top__DOT__u_icache_tag_array_ctrl__DOT__u_icache_tag_array0__DOT__memory;
    std::string icache_top__DOT__u_icache_tag_array_ctrl__DOT__u_icache_tag_array0__DOT__arg_parse_str;
    std::string icache_top__DOT__u_icache_tag_array_ctrl__DOT__u_icache_tag_array0__DOT__code_path;
    std::string icache_top__DOT__u_data_array_ctrl__DOT__u_icache_data_array0__DOT__arg_parse_str;
    std::string icache_top__DOT__u_data_array_ctrl__DOT__u_icache_data_array0__DOT__code_path;
    std::string icache_top__DOT__u_data_array_ctrl__DOT__u_icache_data_array1__DOT__arg_parse_str;
    std::string icache_top__DOT__u_data_array_ctrl__DOT__u_icache_data_array1__DOT__code_path;
    VlTriggerScheduler __VtrigSched_h759a0d49__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vicache_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vicache_top___024root(Vicache_top__Syms* symsp, const char* v__name);
    ~Vicache_top___024root();
    VL_UNCOPYABLE(Vicache_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
